# Generated by Django 4.1.2 on 2022-11-08 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('barberID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barber', models.CharField(max_length=255)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=150)),
                ('barber', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=6)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
            ],
        ),
    ]
